### PR TITLE
Enable authentication before the replica set initialization

### PR DESCRIPTION
**Pull request by perbellinioa**
I've just moved the authentication process before the initialization of the replica. It is useful when the replica set is started with authentication enabled.

### CODE REVIEW

**Comment by gmiroshnykov** [comment]
I'm not sure about the recent versions of MongoDB, but previously you couldn't authenticate before replica set is initialized.

Did the existing approach fail for you in some way?

**Comment by perbellinioa** [comment]
The existing approach was falling for me because I started the replica with the authentication enabled, which imply to be authenticated before to do anything.

**Comment by gmiroshnykov** [comment]
The approach that works for me is following:
1. Start with e.g. three blank MongoDB servers with the same value of `replSet` and `auth=true`
2. Run `rs.initiate()` on one of them
3. Add users
4. Authenticate
5. Run `rs.add(...)` two times to add two remaining servers

You can't authenticate before you run `rs.initiate()` as there are no users in the database yet and there's no way to add them before running `rs.initiate()`.

Are you using a different kind of authentication?

**Comment by perbellinioa** [comment]
I used the approach that is described on MongoDB documentation: 
[Deploy New Replica Set with Access Control!](https://docs.mongodb.org/manual/tutorial/enable-internal-authentication/#deploy-new-replica-set-with-access-control):
- Start one member of the replica set.
- Create administrative users.
- Stop the mongod instance.
- Create the key file to be used by each member of the replica set.
- Copy the key file to each member of the replica set.
- Start each member of the replica set with the appropriate options.
- Connect to the member of the replica set where you created the administrative users.
- Initiate the replica set.
- Verify the initial replica set configuration.
- Add the remaining members to the replica set.
- Check the status of the replica set.
- Create additional users to address operational requirements.

**Comment by gmiroshnykov** [comment]
Wow, okay.
I'm trying really hard not to trashtalk the official approach :)
At least the steps I've described above do not require server restarts.
I guess one could only wish for a declarative configuration...

Any workaround that I can come up with includes some ugly hacks:
We could add a flag to authenticate before `rs.initiate()`.
Or we could try to authenticate both before and after, ignoring any possible errors.
Do you have any suggestions?

Btw, I have to ask - have you already automated the official approach using Ansible?

**Comment by perbellinioa** [comment]
What do you think about the approach on my commit: move the authentication just before the state conditional. The code still check if the user/password are provided if yes try to authenticate else continue.

Yeah, I've already automated the official approach using Ansible.

**Comment by gmiroshnykov** [comment]
The problem is that in my setup I enable auth first, then run `rs.initiate()` and only after that I create users (relying on [localhost exception](https://docs.mongodb.org/manual/core/security-users/#localhost-exception)).

This makes the list of actions required to bootstrap a cluster from scratch much shorter (and, more importantly, idempotent) and do away with multiple changes to config and server restarts.

If I accept this PR as is, that will ruin my use case :(
But I do agree that we should support official approach regardless of my personal opinion on it.
Let me see if I can come up with a change that will work for both approaches...

**Comment by perbellinioa** [comment]
I am wondering why it could be a problem for you? I can imagine you have separated Ansible task to initiate your replica, so if you do not specify the login_user and login_password options it should continue to work. Once you have created the users you can use these options to authenticate.

What do you think about it?

**Comment by gmiroshnykov** [comment]
I think what you say makes sense :)
But we don't have a separate task just for initiating replica set.
One of the requirements we have is to be able to run the same playbooks over and over, so they have to be 100% idempotent.

We're also using Vagrant that basically runs `ansible-playbook -i vagrant site.yml` which brings the whole environment up. When the playbook is changed, you can simply run `vagrant provision` and get your local VM up to date.

**Comment by perbellinioa** [comment]
I see.
In that case, maybe the easiest solution will be to make the change on a different branch labeled "official support" or whatever else.

**Comment by mping** [comment]
Any news on this? I think official approach sucks but should at least be supported.

**Comment by gmiroshnykov** [comment]
I'm sorry, this project is not maintained anymore and I'm going to archive it.

**Pull request closed without merging**
